booking:
  property: Product Profile Dev
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-product

test:
  prodt: Product Profile Dev - Test Updated for Bus and Message Broker again 1A again